INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('2','Personas','/personas','bi bi-people','0');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('2','Clientes','/personas/clientes','bi bi-app','2');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('2','Proveedores','/personas/proveedores','bi bi-app','2');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('2','Personal','/personas/personal','bi bi-app','2');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('2','Heladeros','/personas/heladeros','bi bi-app','2');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('7','Productos','/productos','bi bi-box-seam','0');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('8','Stock','/stock','bi bi-ui-checks-grid','0');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('8','Helados','/stock/helados','bi bi-app','8');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('8','Barquillos','/stock/barquillos','bi bi-app','8');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('8','Baterias','/stock/baterias','bi bi-app','8');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('12','Notas heladero','/nota-heladero/new','bi bi-file-earmark-plus','0');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('13','Facturación','/facturacion','bi bi-file-text','0');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('14','Reportes','/reportes','bi bi-graph-down','0');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('14','Notas heladeros','/reportes/nota-heladeros','bi bi-app','14');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('14','Facturas y Boletas','/reportes/facturas','bi bi-app','14');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('17','Configuración','/configuracion','bi bi-gear','0');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('17','Moneda','/configuracion/monedas','bi bi-app','17');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('17','Marcas','/configuracion/marcas','bi bi-app','17');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('17','Configuración principal','/configuracion/principal','bi bi-app','17');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('17','Locales y series','/configuracion/locales-series','bi bi-app','17');
INSERT INTO destacados(id, nombre, alias, icono, idparent) VALUES ('17','Accesos directos','/configuracion/destacados','bi bi-app','17');